version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Chipzryum/RobloxVS"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"